### PR TITLE
'Toggle secondary profile' system action

### PR DESCRIPTION
**Pull request by spectreseven1138**
Adds a system action and hotkey 'Toggle secondary profile' which toggles between the default profile for the game and a secondary one which is saved as a separate file appended with '-SECONDARY'. Also adds a setting for the toggle popup.
Example usage: Use the select button to toggle gyro camera control on and off using a secondary profile.

(First time contributing on GitHub, hope I'm doing this right)

### CODE REVIEW

**Comment by MERLev** [comment]
Hey
Thank you for participating
Can you pls update the code, to not change titleId variable? Mby just use some global flag instead.
Also, can you pls resolve those warnings on build ?
image

**Comment by spectreseven1138** [comment]
Resolved the overflow warnings, and created a new variable instead of modifying titleid.

**Comment by MERLev** [comment]
Cannot get it to work - when I use hotkey, it shows it's "On" on popup, and never changes to "Off"
Also, as titleid does not have prefix anymore, code for suffix removal inside
onDrawEntry_saveName
sysactions_saveBackup
sysactions_saveRestore
sysactions_saveDelete
is obsolete, is not it? If so, mby remove it too?

**Comment by spectreseven1138** [comment]
To toggle it off, you need to add another 'toggle secondary profile' rule within the secondary profile. Maybe I should make it add one automatically?
Not sure what you mean about titleid not having a suffix. Even though titleid isn't modified in the sysactions_toggleSecondary() function anymore, it is still set to the new value in the (unmodified) profile_load() function. So the suffix removal code is still needed for the save manager functions to work correctly.

**Comment by MERLev** [comment]
To toggle it, i've set up a hotkey under Settings->Hotkeys, which always global, so there was no need to add it as remap. But when using it, it  was showing me only "On" popup.
Onto the titleid yeah, you are right. 
> Can you pls update the code, to not change titleId variable? Mby just use some global flag instead.
By this I meant to leave it without suffix at all, so when title id is needed - there would be no need to remove it. And instead - maybe use global flag for secondary profile.  Do you think you can do it?
Thank you)

**Comment by spectreseven1138** [comment]
You're right, hotkey doesn't toggle off. I'll look into fixing that and also adding a separate flag for the secondary profile.

**Comment by spectreseven1138** [comment]
Fixed hotkey not toggling off, and used a global flag instead of modifying titleid. Also added indicators to the main header and save profile popups to show when secondary profile is enabled.

Also, when loading the secondary profile but there isn't one saved, the current profile is used rather than the global profile.

**Comment by MERLev** [comment]
Good job ! Thank you for contributing)

**Pull request merged**
