### PR TITLE
Added X1Vita to the readme

### PR DESCRIPTION
**Pull request by Ibrahim778**
Added X1Vita to the readme under compatibility.

### CODE REVIEW

**Comment by Ibrahim778** [comment]
Hang on, need to fix bugs.

**Comment by MERLev** [comment]
You may also want to update this page too
https://github.com/MERLev/reVita/wiki/External-Controllers

**Comment by Ibrahim778** [comment]
I will when it's ready

**Comment by MERLev** [comment]
Oh, also, for best compatibility > make hooking on kernel level only
(example)
https://github.com/MERLev/ds34vita/blob/master/main.c
proper mapping for shoulder buttons is also there.

**Comment by Ibrahim778** [comment]
Sure I will. Thanks

**Pull request closed without merging**
